require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'DocumentReader' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' })
  pod 'RNCustomizedImagePicker', :path => '../node_modules/react-native-customized-image-picker'

  pod 'react-native-dl-api', :path => '../node_modules/react-native-dl-api'

  pod 'react-native-progress-bar-android', :path => '../node_modules/@react-native-community/progress-bar-android'

  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'

  post_install do |installer|
    flipper_post_install(installer)
  end
end
